services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
      - wp-website:/var/www/html
    ports:
      - "443:443"
    networks:
      - wp-network
    secrets:
      - ssl_cert
      - ssl_key
    restart:
      on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wp-website:/var/www/html
    networks:
      - wp-network
      - db-network
    restart:
      on-failure

  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb
  #   volumes:
  #     - wp-database:/var/lib/mysql
  #   networks:
  #     - db-network
  #   restart:
  #     on-failure

volumes:
  wp-website:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-website
      o: bind
  
  wp-database:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-database
      o: bind

networks:
  wp-network:
    driver: bridge
  db-network:
    driver: bridge

secrets:
  ssl_cert:
    file: ../secrets/ibertran.42.fr.crt
  ssl_key:
    file: ../secrets/ibertran.42.fr.key
