services:
  nginx:
    build: requirements/nginx
    volumes:
      - wp-website:/website
    ports:
      - "443:443"
    networks:
      - wp-network
    environment:
      - DOMAIN=${DOMAIN}
    secrets:
      - ssl_cert
      - ssl_key
    restart:
      on-failure

  wordpress:
    build:
      context: requirements/wordpress
      args:
        - WP_CLI_URL=${WP_CLI_URL}
    
    volumes:
      - wp-website:/website
    networks:
      - wp-network
      - db-network
    environment:
      - DOMAIN=${DOMAIN}
      - WP_THEME=${WP_THEME}
    secrets:
      -  mysql_database
      -  mysql_user
      -  mysql_password
      -  wp_credentials
    depends_on:
      - mariadb
    restart:
      on-failure

  mariadb:
    build: requirements/mariadb
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - db-network
    secrets:
      -  mysql_root_password
      -  mysql_database
      -  mysql_user
      -  mysql_password
    restart:
      on-failure

  redis:
    build: requirements/redis
    networks:
      - wp-network

  # adminer:
  #   build: requirements/adminer

volumes:
  wp-website:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-website
      o: bind
  
  wp-database:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-database
      o: bind

networks:
  wp-network:
    driver: bridge
  db-network:
    driver: bridge

secrets:
  ssl_cert:
    file: ../secrets/ssl/ibertran.42.fr.crt
  ssl_key:
    file: ../secrets/ssl/ibertran.42.fr.key
  mysql_database:
    file: ../secrets/mariadb/mysql_database.txt
  mysql_root_password:
    file: ../secrets/mariadb/mysql_root_password.txt
  mysql_user:
    file: ../secrets/mariadb/mysql_user.txt
  mysql_password:
    file: ../secrets/mariadb/mysql_password.txt
  wp_credentials:
    file: ../secrets/wordpress/wp_credentials.txt
