services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - main
    secrets:
      - ssl_cert
      - ssl_key
    restart:
      on-failure

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   volumes:
  #     - /home/ibertran/data/wp-database
  #     - /home/ibertran/data/website
  #   networks:
  #     - main
  #     - db
  #   restart:
  #     on-failure

  # mariadb:
  #   build: ./requirements/mariadb
  #   container_name: mariadb
  #   networks:
  #     - db
  #   restart:
  #     on-failure

networks:
  main:
    driver: bridge
  db:
    driver: bridge

secrets:
  ssl_cert:
    file: ../secrets/ibertran.42.fr.crt
  ssl_key:
    file: ../secrets/ibertran.42.fr.key
