services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
      - website:/website
    ports:
      - "443:443"
    networks:
      - website
    environment:
      - DOMAIN=${DOMAIN}
    secrets:
      - ssl_cert
      - ssl_key
      - htpasswd
    depends_on:
      - wordpress
      - proftpd
      - adminer
      - cadvisor
      - react_app
    restart: on-failure

  wordpress:
    build:
      context: requirements/wordpress
      args:
        - WP_CLI_URL=${WP_CLI_URL}
    container_name: wordpress
    volumes:
      - website:/website
    networks:
      - website
      - database
    environment:
      - DOMAIN=${DOMAIN}
      - WP_THEME=${WP_THEME}
      - WP_DEBUG=true
    secrets:
      -  mysql_database
      -  mysql_user
      -  mysql_password
      -  wp_credentials
    depends_on:
      - mariadb
      - redis
    restart: on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - database
    secrets:
      -  mysql_root_password
      -  mysql_database
      -  mysql_user
      -  mysql_password
    restart: on-failure

  proftpd:
    build: requirements/bonus/proftpd
    container_name: proftpd
    volumes:
      - website:/home/www-data
    networks:
      - ftp
    ports:
      - "21:21"
    secrets:
      - proftpd_password
    restart: on-failure

  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - website
    restart: on-failure

  adminer:
    build:
      context: requirements/bonus/adminer
      args:
        - ADMINER_DOWNLOAD_URL=${ADMINER_DOWNLOAD_URL}
    container_name: adminer
    networks:
      - website
      - database
    restart: on-failure

  react_app:
    build: requirements/bonus/react_app
    container_name: react_app
    networks:
      - website
    restart: on-failure
  
  cadvisor:
    build:
      context: requirements/bonus/cadvisor
      args:
        - CADVISOR_DOWNLOAD_URL=${CADVISOR_DOWNLOAD_URL}
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - website
    restart: on-failure

volumes:
  website:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/website
      o: bind
  
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/database
      o: bind

networks:
  website:
    driver: bridge
  database:
    driver: bridge
  ftp:
    driver: bridge

secrets:
  ssl_cert:
    file: ../secrets/ssl/ibertran.42.fr.crt
  ssl_key:
    file: ../secrets/ssl/ibertran.42.fr.key
  mysql_database:
    file: ../secrets/mariadb/mysql_database.txt
  mysql_root_password:
    file: ../secrets/mariadb/mysql_root_password.txt
  mysql_user:
    file: ../secrets/mariadb/mysql_user.txt
  mysql_password:
    file: ../secrets/mariadb/mysql_password.txt
  wp_credentials:
    file: ../secrets/wordpress/wp_credentials.txt
  proftpd_password:
    file: ../secrets/proftpd/proftpd_password.txt
  htpasswd:
    file: ../secrets/htpasswd
