services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
      - wp-website:/website
    ports:
      - "443:443"
    networks:
      - wp-network
    secrets:
      - ssl_cert
      - ssl_key
    restart:
      on-failure

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wp-website:/website
    networks:
      - wp-network
      - db-network
    secrets:
      -  mysql_database
      -  mysql_root_password
      -  mysql_admin
      -  mysql_admin_password
      -  mysql_user
      -  mysql_user_password
    restart:
      on-failure

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - db-network
    secrets:
      -  mysql_database
      -  mysql_root_password
      -  mysql_admin
      -  mysql_admin_password
      -  mysql_user
      -  mysql_user_password
    restart:
      on-failure

volumes:
  wp-website:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-website
      o: bind
  
  wp-database:
    driver: local
    driver_opts:
      type: none
      device: /home/ibertran/data/wp-database
      o: bind

networks:
  wp-network:
    driver: bridge
  db-network:
    driver: bridge

secrets:
  ssl_cert:
    file: ../secrets/ibertran.42.fr.crt
  ssl_key:
    file: ../secrets/ibertran.42.fr.key
  mysql_database:
    file: ../secrets/mysql_database.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_admin:
    file: ../secrets/mysql_admin.txt
  mysql_admin_password:
    file: ../secrets/mysql_admin_password.txt
  mysql_user:
    file: ../secrets/mysql_user.txt
  mysql_user_password:
    file: ../secrets/mysql_user_password.txt
