services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - inception
    restart:
      on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/ibertran/data/wp-database
      - /home/ibertran/data/website
    networks:
      - inception
    restart:
      on-failure

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    restart:
      on-failure

networks:
  inception:
    driver: bridge
