# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile-singlestage                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ibertran <ibertran@student.42lyon.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/22 13:07:50 by ibertran          #+#    #+#              #
#    Updated: 2024/11/22 19:39:31 by ibertran         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

FROM alpine:3.19

RUN apk add --no-cache npm

WORKDIR /app

COPY calculator .

RUN npm install \
	&& npm run build \
	&& npm install -g serve

EXPOSE 3000

ENTRYPOINT [ "serve", "-s", "build" ]
